// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe7I3-joBYmyj5FTtwL5H2KxNRnfB8sBs',
    appId: '1:847496649173:web:b79527f97587e26bed855c',
    messagingSenderId: '847496649173',
    projectId: 'kollektor-839aa',
    authDomain: 'kollektor-839aa.firebaseapp.com',
    storageBucket: 'kollektor-839aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFOepYxMqLRS_GekgyVQECdBV9oXMpago',
    appId: '1:847496649173:android:1d2746a0e963f6beed855c',
    messagingSenderId: '847496649173',
    projectId: 'kollektor-839aa',
    storageBucket: 'kollektor-839aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_wWfgo08crVnA5YFtkEuvWQgmGSolD3s',
    appId: '1:847496649173:ios:b838d80a254648cfed855c',
    messagingSenderId: '847496649173',
    projectId: 'kollektor-839aa',
    storageBucket: 'kollektor-839aa.appspot.com',
    iosBundleId: 'com.example.kollektor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_wWfgo08crVnA5YFtkEuvWQgmGSolD3s',
    appId: '1:847496649173:ios:0d9b2711d91af46eed855c',
    messagingSenderId: '847496649173',
    projectId: 'kollektor-839aa',
    storageBucket: 'kollektor-839aa.appspot.com',
    iosBundleId: 'com.example.kollektor.RunnerTests',
  );
}
